modified:   CMakeLists.txt 	modified:   wiimotedev-daemon

diff --git a/init.d/daemon/slackware/wiimotedev-daemon b/init.d/daemon/slackware/wiimotedev-daemon
--- a/init.d/daemon/slackware/wiimotedev-daemon
+++ b/init.d/daemon/slackware/wiimotedev-daemon
@@ -8,7 +8,18 @@ SERVICE=/usr/sbin/wiimotedev-daemon
 GROUP=wiimotedev
 CONFIG=/etc/wiimotedev/wiimotedev.conf
 
-wiimotedev_start() {
+start() {
+
+  if [ -z $(cat /etc/group | grep $GROUP) ]; then
+    groupadd $GROUP &> /dev/null
+
+    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
+      echo "Cannot add new group $GROUP"
+      exit 1
+    fi
+
+  fi
+
   if [ -f "$PIDFILE" ]; then
     echo "Already running. Please remove $PIDFILE to force start."
     exit 1  
@@ -17,72 +28,58 @@ wiimotedev_start() {
   if [ -x "$SERVICE" ]; then
     ($SERVICE)
   fi
+
 }
 
-wiimotedev_stop() {
+stop() {
+
   if [ -e "$PIDFILE" ]; then
     kill -s QUIT $(cat $PIDFILE) &> /dev/null
     rm -f $PIDFILE &> /dev/null
   else
     echo "Please start service first."
     exit 1
-  fi 
+  fi
+
 }
 
-wiimotedev_reload() {
+reload() {
+
   if [ ! -f "$PIDFILE" ]; then
-    echo " -- \"${PIDFILE}\" file does not exist"
-    exit 1
+    echo "Please run service first."
+    exit 1  
   fi
 
-  if [ ! -f "$CONFIG" ]; then
-    echo " -- \"${CONFIG}\" configuration does not exist"
-    exit 1
-  fi
+  S1=$(dbus-send --system --dest=org.wiimotedev.daemon \
+       --type=method_call --print-reply --reply-timeout=3000 \
+       /service org.wiimotedev.service.dbusReloadSequenceList)
 
-
-  if [ $(cat /proc/$(cat /var/run/wiimotedev-daemon.pid)/cmdline) != $SERVICE ]; then
-    echo " -- Unable to find service"
-    exit 1
-  fi
-
-  S1=$(dbus-send \
-            --system \
-            --dest=org.wiimotedev.daemon \
-	    --type=method_call \
-	    --print-reply \
-	    --reply-timeout=3000 \
-	    /service \
-	    org.wiimotedev.service.dbusReloadSequenceList)
-
-  if [ -n "$(echo ${S1} | grep "boolean true")" ]; then
-    echo " -- Configuration reloaded successful"
-  else
-    echo " -- Cannot reload configuration, dbus fail?"
+  if [ ! -n "$(echo ${S1} | grep "boolean true")" ]; then
     exit 1
   fi
   
 }
 
 case "$1" in
-    start)
-	echo "Starting Wiimotedev-daemon"
-        wiimotedev_start
-        ;;
-    stop)
-	echo "Stopping Wiimotedev-daemon"
-        wiimotedev_stop
-        ;;
-    restart)
-	echo "Restarting Wiimotedev-daemon"
-        wiimotedev_stop
-        wiimotedev_start
-        ;;
-    reload)
-	echo "Reloading Wiimotedev-daemon"
-	wiimotedev_reload
-        ;;
-    *)
-        echo $"Usage: $0 {start | stop | reload | restart }"
-        ;;
+  start)
+    echo "Starting Wiimotedev-daemon"
+    start
+    ;;
+  stop)
+    echo "Stopping Wiimotedev-daemon"
+    stop
+    ;;
+  restart)
+    echo "Stopping Wiimotedev-daemon"
+    stop
+    echo "Starting Wiimotedev-daemon"
+    start
+    ;;
+  reload)
+    echo "Reloading Wiimotedev-daemon"
+    reload
+    ;;
+  *)
+    echo $"Usage: $0 {start | stop | reload | restart }"
+    ;;
 esac
