Update wiimotedev-client stack. 	modified:   CMakeLists.txt 	copied:     ubuntu/CMakeLists.txt -> arch/CMakeLists.txt 	new file:   arch/wiimotedev-client 	modified:   debian/CMakeLists.txt 	modified:   debian/wiimotedev-client 	modified:   gentoo/CMakeLists.txt 	modified:   gentoo/wiimotedev-client 	modified:   slackware/CMakeLists.txt 	modified:   slackware/wiimotedev-client 	modified:   ubuntu/CMakeLists.txt 	modified:   ubuntu/wiimotedev-client

diff --git a/init.d/client/gentoo/wiimotedev-client b/init.d/client/gentoo/wiimotedev-client
--- a/init.d/client/gentoo/wiimotedev-client
+++ b/init.d/client/gentoo/wiimotedev-client
@@ -8,66 +8,57 @@ SERVICE=/usr/sbin/wiimotedev-client
 GROUP=wiimotedev
 CONFIG=/etc/wiimotedev/client.conf
 
-opts="reload"
-
-# int wiimotedev_check_group()
-
-function wiimotedev_check_group {
-  if [ -z $(cat /etc/group | grep "$GROUP") ]; then
-    echo " -- Adding new group \"${GROUP}\""
-    groupadd $GROUP
-
-    if [ -n $(cat /etc/group | grep "$GROUP") ]; then
-      echo " -- Group \"${GROUP}\" added successful"
-    else
-      echo " -- Cannot add new group \"${GROUP}\""
-      return 1
-    fi
-  fi
-}
-
-# int wiimotedev_start()
-
-function wiimotedev_start() {
-  wiimotedev_check_group
-
-  if [ ! -x $SERVICE ]; then
-    echo " -- ${SERVICE} file is not executable"
-    return 1
-  fi
-
-  start-stop-daemon --start -q -x "$SERVICE" --group "$GROUP"
-}
-
-# int wiimotedev_stop()
-
-function wiimotedev_stop() {
-  wiimotedev_check_group
-
-  if [ -f "$PIDFILE" ]; then
-    start-stop-daemon --stop -q -p "$PIDFILE" --group "$GROUP"
-  fi
-}
-
 depend() {
 	need dbus 
+	after wiimotedev-daemon
 }
 
 start() {
-	ebegin "Starting wiimotedev-client"
-	wiimotedev_start
-	eend $?
-}
+  ebegin "Starting Wiimotedev-client"
 
-restart() {
-	ebegin "Restarting wiimotedev-client"
-	wiimotedev_start
-	wiimotedev_stop
-	eend $?
+  if [ -z $(cat /etc/group | grep $GROUP) ]; then
+    groupadd $GROUP &> /dev/null
+
+    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
+      eend 1
+      echo "Cannot add new group $GROUP"
+      exit 1
+    fi
+
+  fi
+
+  if [ -f "$PIDFILE" ]; then
+    eend 1
+    echo "Already running. Please remove $PIDFILE to force start."
+    exit 1  
+  fi
+  
+  if [ -x "$SERVICE" ]; then
+    start-stop-client --start -q -x "$SERVICE" --group "$GROUP"
+  fi
+
+  eend 0
 }
 
 stop() {
-	ebegin "Stopping wiimotedev-client"
-	wiimotedev_stop
-	eend $?
+  ebegin "Stopping Wiimotedev-client"
+
+  if [ -f "$PIDFILE" ]; then
+    kill -s 3 $(cat $PIDFILE) &> /dev/null
+    rm -f $PIDFILE &> /dev/null
+  else
+    eend 1
+    echo "Please start service first."
+    exit 1
+  fi
+
+  eend 0
 }
+
+restart() {
+	stop
+        sleep 1
+	start
+}
+
+
diff --git a/init.d/client/slackware/wiimotedev-client b/init.d/client/slackware/wiimotedev-client
--- a/init.d/client/slackware/wiimotedev-client
+++ b/init.d/client/slackware/wiimotedev-client
@@ -4,37 +4,62 @@
 # Contact: public@santyago.pl
 
 PIDFILE=/var/run/wiimotedev-client.pid
+SERVICE=/usr/sbin/wiimotedev-client
+GROUP=wiimotedev
+CONFIG=/etc/wiimotedev/client.conf
 
-wiimotedev_start() {
-  if [ -x /usr/sbin/wiimotedev-client ]; then
-    /usr/sbin/wiimotedev-client
+start() {
+
+  if [ -z $(cat /etc/group | grep $GROUP) ]; then
+    groupadd $GROUP &> /dev/null
+
+    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
+      echo "Cannot add new group $GROUP"
+      exit 1
+    fi
+
   fi
+
+  if [ -f "$PIDFILE" ]; then
+    echo "Already running. Please remove $PIDFILE to force start."
+    exit 1
+  fi
+
+  if [ -x "$SERVICE" ]; then
+    ($SERVICE)
+  fi
+
 }
 
-wiimotedev_stop() {
-  if [ -e "$PIDFILE" ]; then
-    kill $(cat $PIDFILE)
-    rm -f $PIDFILE
+stop() {
+
+  if [ -f "$PIDFILE" ]; then
+    kill -s 3 $(cat $PIDFILE) &> /dev/null
+    rm -f $PIDFILE &> /dev/null
+  else
+    echo "Please start service first."
+    exit 1
   fi
-  killall wiimotedev-client 1> /dev/null 2> /dev/null
+
 }
 
 case "$1" in
-    start)
-	echo "Starting wiimotedev-client"
-        wiimotedev_start
-        ;;
-    stop)
-	echo "Stopping wiimotedev-client"
-        wiimotedev_stop
-        ;;
-    restart)
-	echo "Restarting wiimotedev-client"
-        wiimotedev_stop
-        sleep 1
-        wiimotedev_start
-        ;;
-    *)
-        echo $"Usage: $0 {start | stop | restart }"
-        ;;
+  start)
+    echo "Starting Wiimotedev-client"
+    start
+    ;;
+  stop)
+    echo "Stopping Wiimotedev-client"
+    stop
+    ;;
+  restart)
+    echo "Stopping Wiimotedev-client"
+    stop
+    sleep 1
+    echo "Starting Wiimotedev-client"
+    start
+    ;;
+  *)
+    echo $"Usage: $0 {start | stop | restart }"
+    ;;
 esac
diff --git a/init.d/client/ubuntu/wiimotedev-client b/init.d/client/ubuntu/wiimotedev-client
--- a/init.d/client/ubuntu/wiimotedev-client
+++ b/init.d/client/ubuntu/wiimotedev-client
@@ -1,16 +1,15 @@
+#! /bin/sh
 # Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
 # Copyright (C) 2010 Jarek Bojko
-# Contact: vazir.pl@gmail.com      
-
-#! /bin/sh
+# Contact: vazir.pl@gmail.com
 
 ### BEGIN INIT INFO
-# Provides:          Wiimotedev
+# Provides:          wiimotedev-client
 # Required-Start:    bluetooth
 # Required-Stop:     bluetooth
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Wiimotedev client
+# Short-Description: wiimotedev client
 ### END INIT INFO
 
 PIDFILE=/var/run/wiimotedev-client.pid
@@ -18,64 +17,59 @@ SERVICE=/usr/sbin/wiimotedev-client
 GROUP=wiimotedev
 CONFIG=/etc/wiimotedev/client.conf
 
-# int wiimotedev_check_group()
+start() {
 
-wiimotedev_check_group() {
-  if [ -z $(cat /etc/group | grep "$GROUP") ]; then
-    echo " -- Adding new group \"${GROUP}\""
-    groupadd $GROUP
+  if [ -z $(cat /etc/group | grep $GROUP) ]; then
+    groupadd $GROUP &> /dev/null
 
-    if [ -n $(cat /etc/group | grep "$GROUP") ]; then
-      echo " -- Group \"${GROUP}\" added successful"
-    else
-      echo " -- Cannot add new group \"${GROUP}\""
-      return 1
+    if [ ! -n $(cat /etc/group | grep $GROUP) ]; then
+      echo "Cannot add new group $GROUP"
+      exit 1
     fi
+
   fi
-}
-
-# int wiimotedev_start()
-
-wiimotedev_start() {
-  wiimotedev_check_group
-
-  if [ ! -x $SERVICE ]; then
-    echo " -- ${SERVICE} file is not executable"
-    return 1
-  fi
-
-  start-stop-daemon --start -q -x "$SERVICE" --group "$GROUP"
-}
-
-# int wiimotedev_stop()
-
-wiimotedev_stop() {
-  wiimotedev_check_group
 
   if [ -f "$PIDFILE" ]; then
-    start-stop-daemon --stop -q -p "$PIDFILE" --group "$GROUP"
+    echo "Already running. Please remove $PIDFILE to force start."
+    exit 1
   fi
+
+  if [ -x "$SERVICE" ]; then
+    start-stop-client --start -q -x "$SERVICE" --group "$GROUP"
+  fi
+
 }
 
+stop() {
 
-# int wiimotedev_reload()
+  if [ -f "$PIDFILE" ]; then
+    start-stop-client --stop -q -p "$PIDFILE" --group "$GROUP"
+    rm -f $PIDFILE &> /dev/null
+  else
+    echo "Please start service first."
+    exit 1
+  fi
+
+}
 
 case "$1" in
   start)
-    echo "Starting wiimotedev-client"
-    wiimotedev_start
+    echo "Starting Wiimotedev-client"
+    start
     ;;
   stop)
-    echo "Stopping wiimotedev-client"
-    wiimotedev_stop
+    echo "Stopping Wiimotedev-client"
+    stop
     ;;
   restart)
-    echo "Restarting wiimotedev-client"
-    wiimotedev_stop
-    wiimotedev_start
+    echo "Stopping Wiimotedev-client"
+    stop
+    sleep 1
+    echo "Starting Wiimotedev-client"
+    start
     ;;
   *)
-    echo "Usage (start | stop | restart)"
+    echo $"Usage: $0 {start | stop | restart }"
     ;;
 esac
 
