Update gentoo init.d script. Support reload and restart opts.

diff --git a/initd/gentoo/wiimotedev-daemon b/initd/gentoo/wiimotedev-daemon
--- a/initd/gentoo/wiimotedev-daemon
+++ b/initd/gentoo/wiimotedev-daemon
@@ -3,18 +3,118 @@
 # Copyright (C) 2010 Bartłomiej Burdukiewicz
 # Contact: dev.strikeu@gmail.com   
 
+#!/sbin/runscript
+# Distributed under the terms of the GNU Lesser General Public License, v2.1 or later
+# Copyright (C) 2010 Bartłomiej Burdukiewicz
+# Contact: dev.strikeu@gmail.com   
+
+PIDFILE=/var/run/wiimotedev-daemon.pid
+SERVICE=/usr/sbin/wiimotedev-daemon
+GROUP=wiimotedev
+CONFIG=/etc/wiimotedev/wiimotedev.conf
+
+opts="reload"
+
+# int wiimotedev_check_group()
+
+function wiimotedev_check_group {
+  if [ -z $(cat /etc/group | grep "$GROUP") ]; then
+    echo " -- Adding new group ${GROUP}"
+    groupadd $GROUP
+
+    if [ -n $(cat /etc/group | grep "$GROUP") ]; then
+      echo " -- Group ${GROUP} added successful"
+    else
+      echo " -- Cannot add new group \"${GROUP}\""
+      return 1
+    fi
+  fi
+}
+
+# int wiimotedev_start()
+
+function wiimotedev_start() {
+  wiimotedev_check_group
+
+  if [ ! -x $SERVICE ]; then
+    echo " -- ${SERVICE} file is not executable"
+    return 1
+  fi
+
+  start-stop-daemon --start -q -x "$SERVICE" --group "$GROUP"
+}
+
+# int wiimotedev_stop()
+
+function wiimotedev_stop() {
+  if [ -f "$PIDFILE" ]; then
+    start-stop-daemon --stop -q -p "$PIDFILE" --group "$GROUP"
+  fi
+}
+
+
+# int wiimotedev_reload()
+
+function wiimotedev_reload() {
+  if [ ! -f "$PIDFILE" ]; then
+    echo " -- ${PIDFILE} file does not exist"
+    return 1
+  fi
+
+  if [ ! -f "$CONFIG" ]; then
+    echo " -- ${CONFIG} configuration does not exist"
+    return 1
+  fi
+
+
+  if [ $(cat /proc/$(cat /var/run/wiimotedev-daemon.pid)/cmdline) != $SERVICE ]; then
+    echo " -- Unable to find service"
+    return 1
+  fi
+
+  S1=$(dbus-send \
+            --system \
+            --dest=org.wiimotedev.daemon \
+	    --type=method_call \
+	    --print-reply \
+	    --reply-timeout=3000 \
+	    /service \
+	    org.wiimotedev.service.dbusReloadSequenceList)
+
+  if [ -n "$(echo ${S1} | grep "boolean true")" ]; then
+    echo " -- Configuration reloaded successful"
+  else
+    echo " -- Cannot reload configuration, dbus fail?"
+    return 1
+  fi
+  
+}
+
 depend() {
 	need dbus bluetooth
 }
 
 start() {
 	ebegin "Starting Wiimotedev-daemon"
-        start-stop-daemon --start -q --exec /usr/sbin/wiimotedev-daemon
+	wiimotedev_start
+	eend $?
+}
+
+restart() {
+	ebegin "Restarting Wiimotedev-daemon"
+	wiimotedev_start
+	wiimotedev_stop
+	eend $?
+}
+
+reload() {
+	ebegin "Reloading Wiimotedev-daemon"
+	wiimotedev_reload
 	eend $?
 }
 
 stop() {
 	ebegin "Stopping Wiimotedev-daemon"
-	start-stop-daemon --stop -q --pidfile /var/run/wiimotedev-daemon.pid
+	wiimotedev_stop
 	eend $?
 }
